Added security & specification blocks to details page
GovAlta/dcp-monorepo pull request #98
Opened 2024-04-29 18:00 UTC by Steve-Rozeboom

2024-04-30 00:06 UTC, smettu007 requested changes

2024-04-30 00:06 UTC, smettu007 commented on apps/common-capabilities/src/pages/details/index.tsx
> -  useEffect(() => {
do not delete this useEffect! make sure your new code changes for the security table are additions to the content to show both in the sidebar and in the body! We have the code here as it is due to the fact that its easy to read and maintain

2024-04-30 00:06 UTC, smettu007 commented on apps/common-capabilities/src/pages/details/index.tsx
> -  const contentToShow = [
please do not delete this code, as they are here to maintain the dynamic content display easy!

2024-04-30 00:06 UTC, smettu007 commented on apps/common-capabilities/src/pages/[slug].astro
> +  <Details client:load app={app} fields={jsondata.fields} />
please define these fields within the Details component via code! Things that are specific to the component are better off defining them in the code rather than reading it from a file! We follow functional programming, everything that the function needs, should be encapsulated within the function. i.e JSON field names etc...

2024-04-30 00:06 UTC, smettu007 commented on apps/common-capabilities/src/pages/[slug].astro
> +//import { services as apps } from '../content/datastore.json';
revert this code

2024-04-30 00:06 UTC, smettu007 commented on apps/common-capabilities/src/pages/details/styles.css
> +.security {border: none; border-collapse: collapse; margin-bottom: 30px; margin-left: 0px;}
we dont have to implement the css for the table if you use the table component from the design system

2024-04-30 00:06 UTC, smettu007 commented on apps/common-capabilities/src/pages/details/styles.css
> +.p {border: 1px solid green;}
make use of design tokens here https://github.com/GovAlta/design-tokens/blob/main/dist/tokens.css for representing colors and other parameterized values

2024-04-30 00:06 UTC, smettu007 commented on apps/common-capabilities/src/pages/details/styles.css
> +  font-size: 2em;
use design tokens to use font-size value https://github.com/GovAlta/design-tokens/blob/main/dist/tokens.css

2024-04-30 00:06 UTC, smettu007 commented on apps/common-capabilities/src/pages/details/index.tsx
> +          <tr key={id}>
again, use table from design system components rather than custom code

2024-05-08 19:18 UTC, closed without merging

2024-05-08 19:20 UTC, Steve-Rozeboom commented
Multiple changes to the remote files, made this PR outdated